version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.5-jdk-11
      - image: mysql:8.0.29-oracle
        environment:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_USER: springTest
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: testdb
      - image: vromero/activemq-artemis:latest
    steps:
      - checkout
      - run:
          name: Install
          command: mvn install -DskipTests
      - run:
          name: Initialize database schema/tables
          command: mvn -pl database flyway:migrate
      - run:
          name: Run tests
          command: mvn test