version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.5-jdk-11
      - image: mysql:8.0.29-oracle
        environment:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_USER: springTest
          MYSQL_PASSWORD: test
    steps:
      - checkout
      - run:
          name: Install annotation processor
          command: mvn -Duser.home=/var/maven install -P dev
      - run:
          name: Install database module
          command: mvn -Duser.home=/var/maven -pl database install
      - run:
          name: Initialize database schema/tables
          command: mvn -Duser.home=/var/maven -pl database flyway:migrate -P dev
      - run:
          name: Run tests
          command: mvn -Duser.home=/var/maven test
